### PR TITLE
fixes and refactors

### PR DESCRIPTION
**Pull request by solareon**
Corrects multiple linting errors and replaces N0_ calls with natives. Also moves sound ping into function vice idle thread. Removes references to cache.ped as this is an ox_lib function.

### CODE REVIEW

**Comment by PenguScript** [comment]
This doesn't work. Please fix if you'd like this to be merged.

**Comment by PenguScript** [comment]
I'll keep in open for now.

**Comment by solareon** [comment]
@PenguScript I'm confused. The export was misnamed but even fixing that on your original it doesn't do anything? Are you supposed to add some weapon_digiscanner?

**Comment by PenguScript** [comment]
The issue was when you go to view the scanner, it flickers then goes blackscreen

**Comment by PenguScript** [comment]
it was the same result on multiple clients

**Comment by zexproof** [comment]
I've got this issue with scanner, not sure what it is.

Screenshot 2024-01-26 233131

**Pull request closed without merging**
